name: 'Build and push images'
description: 'Build and push the docker images for the p1 system to docker hub'
inputs:
  image:
    description: 'registry + image name'
    required: true
    default: 'docker.io/tijsvanerp/vanerp.io'
  folder:
    description: 'Folder to build from'
    required: true
    default: 'persister'
  tags:  # id of input
    description: 'Tags for the docker image'
    required: true
    default: |
      type=semver,prefix=persister-,suffix=,pattern=v{{version}}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
    - name: Install dependencies
      run: go get ./${{ inputs.who-to-greet }}
    - name: Test with the Go CLI
      run: go test ./${{ inputs.who-to-greet }}/...

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: ${{ inputs.who-to-greet }}
    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/arm64,linux/arm/v7
        file: ${{ inputs.who-to-greet }}/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
